### ISSUE TITLE
Support broadcast as a routing option for parallel regions.

### ISSUE THREAD

**Issue by wmarshall484** [IBMStreams/streamsx.topology#1460]
A parallel region should support the option of having all incident tuples broadcast to every channel.

At the functional API level, this could look like:
```Java
// In Java
TStream<Integer> stream = stream.parallel(() -> 5, Routing.BROADCAST)
```

or
```python
#python
s = s.parallel(width = 5, routing = topology.Routing.BROADCAST)
```

Ref: https://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.1/com.ibm.streams.ref.doc/doc/udpparallelannotation.html

- [x] #1542 Java api & implementation for `TStream` and SPL code generation
- [x] #1563 Support for Java `SPLStream`
- [x] #1596 Support for Python.

**Comment by ddebrunner** [comment]
Just to note that this is a new feature in Streams 4.2

**Comment by ddebrunner** [comment]
Also typically to be useful depends on the ability to have multiple separate inputs to a parallel region.

**Comment by wmarshall484** [comment]
Notes:
* Required to support parallel streams in the Beam runner.
* Adjacent parallel regions with broadcast enabled will generate tuples exponentially since every channel broadcasts to every downstream channel.

**Comment by ddebrunner** [comment]
> Adjacent parallel regions with broadcast enabled will generate tuples exponentially

**May** generate tuples exponentially, we have no idea what the first region is doing with the tuples, so the number output is not guaranteed to be order(total number in across all channels).

Not sure what should be documented, apart from the simple statement tuples are broadcast to all channels.
