### ISSUE TITLE
Support complete job config overlay files.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1525]
`JobConfig` provides a logical view of the job config overlay and provides the ability to add in raw overlay information. This is used by `streamsx-runner` and `Topology` submission.

However the output of the `Topology` submission is a JSON file containing the complete overlay, this currently cannot be used by either submission method. In addition complete files may exist for existing SPL projects.

So if one builds a bundle using `BUNDLE` context, you cannot use the resultant job config overlay JSON as-is on a subsequent `streamsx-runner` invocation.

Proposing:

- [x] Add support for a comment (#1532)
- [x] Add method to get the full overlay  (#1532)
- [x] Static methods in `JobConfig` to create an instance from a file or dict. (#1534)
- [x] Addition arguments to `streamsx-runner` to fully support job config overlays. (#1547)
- [ ] Support raw overlay additions with `streamsx-runner`
- [ ] Update `streamsx-runner` doc page.

Ref: https://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.1/com.ibm.streams.ref.doc/doc/submitjobparameters.html

**Comment by markheger** [comment]
* same feature set as streamsx-streamtool submitjob
* documentation describes job-config-overlays
